.R1
no-label-in-reference
accumulate
.R2
.TL
Räta linjen
.AU
cytopyge

.NH	1
Räta linjens ekvation
.[
math_exponent_2c
.]
.NH	2
k form
.EQ
y=kx+m
.EN
.NH	2
allmän form
.EQ
ax+by+c=0
.EN
.NH	2
enpunkts from
.EQ
(y - y sub 1 ) = k(x - x sub 1 )
.EN

.NH	1
Riktningscoefficient
.EQ
k
= {DELTA y} over {DELTA x}
= {y sub 2 - y sub 1} over {x sub 2 - x sub 1}
.EN

.NH	1
Vinkelräta linjer
.PP
för linjer med k-värde
.EQ
k sub 1 \[pc] k sub 2 = -1
.EN
