.TL
Number theory
.AU
cytopyge

.NH	1
Natural numbers (N)
.EQ
x-2=0	\[rA]	x=2
.EN

.NH 1
Whole numbers (Z)
.EQ
x+2=0	\[rA]	x=-2
.EN
.EQ
N \[mo] Z
.EN

.NH 1
Rational numbers (Q)
.EQ
2x-1=0	\[rA]	x=- 1 over 2
.EN
.EQ
Z \[mo] Q
.EN

.NH 1
Real numbers (R)
.EQ
x sup 2 - 2 = 0	\[rA]	x= \[u00B1] sqrt 2
.EN
.EQ
Q \[mo] R
.EN

.NH 1
Complex numbers (C)
.EQ
x sup 2 + 1 = 0	\[rA]	x= \[u00B1] sqrt -1 = \[u00B1] i
.EN
.EQ
R \[mo] C
.EN
