#!/bin/bash


#create config dir
[ -d ~/.config/hosts ] || mkdir ~/.config/hosts
cd ~/.config/hosts
git init


# copy original /etc/hosts to [master]
[ -f /etc/hosts.org ] || cp /etc/hosts /etc/hosts.org
cp /etc/hosts.org ~/.config/hosts/hosts
git add ~/.config/hosts/hosts
git commit -a -m 'created with script'


# create blacklist hosts file in [blacklist]
git branch blacklist
git checkout blacklist
curl https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts > ~/.config/hosts/hosts
git add ~/.config/hosts/hosts
git commit -a -m 'created with script'


# point /etc/hosts to ~/.config/hosts/hosts as symlink
sudo ln -sf ~/.config/hosts/hosts /etc/hosts


# now you can alter hosts versions with git checkout
## to original /etc/hosts with:
### git checkout master
## to blacklist hosts with:
### git checkout blacklist


# update blacklist

cd ~/.config/hosts
git checkout blacklist
cp hosts archive/`date +%Y%m%d_%H%M%S`_archived_hosts
curl https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts > ~/.config/hosts/hosts
git add ~/.config/hosts/hosts
git commit -a -m 'updated with script'
sudo ln -sf ~/.config/hosts/hosts /etc/hosts
printf "hosts blacklist updated succesfully\n"
