#!/usr/bin/env bash

[[ -n $GNUPGHOME ]] || export GNUPGHOME="$HOME/.config/gnupg"

# correct ownership
chown -R $(id -un):$(id -gn) $GNUPGHOME

# correct permissions
## for files
find $GNUPGHOME -type f -exec chmod 600 {} \;
## for directories
find $GNUPGHOME -type d -exec chmod 700 {} \;

