#!/usr/bin/env bash

# ansi

## terminal escape code
tec='\033['	# or tecs='\e['
mode='m'

# text

## color
black='30'
red='31'
green='32'
yellow='33'
blue='34'
magenta='35'
cyan='36'
white='37'

## background color
blackbg='40'
redbg='41'
greenbg='42'
yellowbg='43'
bluebg='44'
magentabg='45'
cyanbg='46'
whitebg='47'

## high intensity color
blackhi='90'
redhi='91'
greenhi='92'
yellowhi='93'
bluehi='94'
magentahi='95'
cyanhi='96'
whitehi='97'

## background high intensity color
blackbghi='100'
redbghi='101'
greenbghi='102'
yellowbghi='103'
bluebghi='104'
magentabghi='105'
cyanbghi='106'
whitebghi='107'

## attribute
reset='0'
bold='1'
dim='2'
smso='3'
ul='4'
blink='5'
six='6'
rev='7'
invis='8'
nine='9'

end="$tec$reset$mode"

text='hello'
echo -en "$tec$whitehi;$redbg$mode$text$end"
printf "$tec$whitehi;$redbg$mode%s$end" "$text"
echo

#printf "$(declare -p)"

# tput color
## see man terminfo under string capabilities

tblack=$(tput setaf 0)
tred=$(tput setaf 1)
tgreen=$(tput setaf 2)
tyellow=$(tput setaf 3)
tblue=$(tput setaf 4)
tmagenta=$(tput setaf 5)
tcyan=$(tput setaf 6)
twhite=$(tput setaf 7)
tdefault=$(tput setaf 9)

## tput background color
tblackbg=$(tput setab 0)
tredbg=$(tput setab 1)
tgreenbg=$(tput setab 2)
tyellowbg=$(tput setab 3)
tbluebg=$(tput setab 4)
tmagentabg=$(tput setab 5)
tcyanbg=$(tput setab 6)
twhitebg=$(tput setab 7)
tdefaultbg=$(tput setab 9)

## tput attribute
treset=$(tput sgr0)
tbold=$(tput bold)
tdim=$(tput dim)
smso=$(tput smso)
tul=$(tput smul)
tblink=$(tput blink)
#six='6'
trev=$(tput rev)
invis=$(tput invis)
#nine='9'
ital=$(tput sitm)
shadow=$(tput sshm)
stout=$(tput smso)
sub=$(tput ssubm)
sup=$(tput ssupm)

#declare -p | grep '\-\-'

ttext='howdy'
$twhite; $tredbg; echo -en $ttext; $treset
$twhite; $tredbg; printf "$ttext"; $treset




: '
# palette
#
# base16-shell (https://github.com/chriskempson/base16-shell)
# Base16 Shell template by Chris Kempson (http://chriskempson.com)
# IR Black scheme by Timothée Poisot (http://timotheepoisot.fr)

color00="00/00/00" # Base 00 - Black
color01="ff/6c/60" # Base 08 - Red
color02="a8/ff/60" # Base 0B - Green
color03="ff/ff/b6" # Base 0A - Yellow
color04="96/cb/fe" # Base 0D - Blue
color05="ff/73/fd" # Base 0E - Magenta
color06="c6/c5/fe" # Base 0C - Cyan
color07="b5/b3/aa" # Base 05 - White
color08="6c/6c/66" # Base 03 - Bright Black
color09=$color01 # Base 08 - Bright Red
color10=$color02 # Base 0B - Bright Green
color11=$color03 # Base 0A - Bright Yellow
color12=$color04 # Base 0D - Bright Blue
color13=$color05 # Base 0E - Bright Magenta
color14=$color06 # Base 0C - Bright Cyan
color15="fd/fb/ee" # Base 07 - Bright White
color16="e9/c0/62" # Base 09
color17="b1/8a/3d" # Base 0F
color18="24/24/22" # Base 01
color19="48/48/44" # Base 02
color20="91/8f/88" # Base 04
color21="d9/d7/cc" # Base 06
color_foreground="b5/b3/aa" # Base 05
color_background="00/00/00" # Base 00


# color info
# https://www.color-hex.com

# sway colors
bluetooth_blue				#96cbfe
ip_ex_blue					#005577
old_ip_ex_blue				#4c7899
light_grey_sel_text			#bbbbbb
highlight_text				#ffffff
time_yellow					#ffffb6
dark_grey_non_sel_text		#999999
active_window_box_text		#ffffff
active_window_box_bg		#005577
cursor_pink					#ff73fd

--key-hl-color			800080 \
--ring-color			080808 \
--text-color			800000 \
--text-clear-color		808000 \
--text-ver-color		800080 \
--text-wrong-color		800000
# '
