#!/bin/bash

## keys (i) bigger than 128 characters create different results
## between aegis and genotp
## a random key of 64 alphanumeric characters did work with:
## '< /dev/random tr -d -c "[:alnum:]" | head -c 64 | wl-copy'

read i

i_base32=$(printf "$i" | base32 -i)

printf "$i_base32" > $HOME/_git/private/vault/totp.key
printf "$i_base32\n"
printf "$i_base32" | qrencode -t UTF8
